### ISSUE TITLE
dokka Gradle plugin doesn't work with Kotlin 1.2

### ISSUE THREAD

**Issue by eskatos** [Kotlin/dokka#265]
Upgrading some builds to Gradle 4.5 that embedd Kotlin 1.2 made the `dokka` task to fail.

Here are two examples:

[Using dokka 0.9.15](https://scans.gradle.com/s/tg4ylkn6j6vlu/failure?openFailures=WzBd&openStackTraces=W3t9LDBd#top=0)
`java.lang.NoSuchMethodError: kotlin.reflect.jvm.internal.KClassImpl.getMembers(Lkotlin/reflect/jvm/internal/impl/resolve/scopes/MemberScope;ZZZ)Lkotlin/sequences/Sequence;`

[Using dokka 0.9.16-eap-2](https://scans.gradle.com/s/52fpz73prgcdc/failure?openFailures=WzBd&openStackTraces=WzEse31d#top=0)
`java.lang.NoClassDefFoundError: kotlin/reflect/KClasses`

This is apparently due to this [breaking change in 1.2](http://kotlinlang.org/docs/reference/whatsnew12.html#kotlin-standard-library-artifacts-and-split-packages): 

> Another change made to ensure compatibility with the new module system is removing the deprecated declarations in the `kotlin.reflect` package from the `kotlin-reflect` library. If you were using them, you need to switch to using the declarations in the `kotlin.reflect.full` package, which is supported since Kotlin 1.1.

**Comment by greenrobot** [comment]
Also had the error with Gradle 4.5 and is gone after downgrading to 4.4.1 again.

**Comment by edeandrea** [comment]
Same here as well. This breaks my upgrades to Gradle 4.5.

**Comment by edeandrea** [comment]
Here's a test project that demonstrates the error
[kotlin-test.zip](https://github.com/Kotlin/dokka/files/1668828/kotlin-test.zip)

**Comment by edeandrea** [comment]
I also posted gradle/gradle#4171

**Comment by edeandrea** [comment]
So based on outcome of gradle/gradle#4171 this problem is Dokka's problem, not Gradle's. Those of us who use Dokka are stuck with Gradle 4.4.1 until the Dokka team fixes this.

**Comment by sid9102** [comment]
@semoro This is breaking my builds. I've had to disable the dokka plugin for the time being. An ETA on a fix would really be appreciated! Thanks in advance!

**Comment by dmarin** [comment]
@semoro an ETA would be appreciated, so we can decide what suits as better. Thanks!

**Comment by semoro** [comment]
Hi! I'm working on fix right now

**Comment by dmarin** [comment]
thanks, please, let me know if you need some beta testers for this fix :)

**Comment by semoro** [comment]
Fixed in new EAP
https://github.com/Kotlin/dokka/releases/tag/0.9.16-eap-3

**Comment by dmarin** [comment]
Thanks for the quick fix @semoro, just tested it and it is working! :)

**Comment by jaredsburrows** [comment]
@semoro Since this is just a patch, why make it an EAP? Can you just bump to `0.9.16` release?

**Comment by stevesamknows** [comment]
(Late to the party as usual, but posting in case it's useful for others)
Strange, was on 0.9.16 and encountered this problem; upgrading to 0.9.17 fixed it
