### ISSUE TITLE
Implement an error message for unsupported Gradle versions

### ISSUE THREAD

**Issue by kamildoleglo** [Kotlin/dokka#1426]
Right now dokka fails with an exception like `java.lang.NoSuchMethodError:kotlin.jvm.internal.Reflection.typeOf(Ljava/lang/Class;)Lkotlin/reflect/KType;`
while it should display a meaningful message instead

**Comment by wei120698598** [comment]
How to fix it ?

**Comment by arpitagarwal1301** [comment]
Facing the same issue . Any possible reason or fix ??

**Comment by kamildoleglo** [comment]
Dokka from 1.4.30 supports only Gradle 5+ if I'm not mistaken (or maybe even 5.5+, not sure right now) so you just have to update your Gradle version

**Comment by chreck** [comment]
It worked on my end with `gradle-6.7.1`

**Comment by MarcinAman** [comment]
Dokka should work on gradle newer or equal 5.6. Right it can't work without kotlin plugin, so you might want to also check out their compatibility list, but as a rule of thumb everything that starts with 6.X or 7.X should be fine.
